const btnNewTask=document.querySelector(".new-task-btn"),modal=document.querySelector(".modal"),form=document.querySelector(".modal__form"),input=document.querySelector(".modal__input--title"),inputDesc=document.querySelector(".modal__input--textarea"),checkBoxesContainer=document.querySelector(".modal__checkboxes"),textLength=document.querySelector(".text-length"),checkBoxes=document.querySelectorAll(".checkbox-proprity"),limitClass=document.querySelectorAll(".limit"),tasksList=document.querySelector(".task__list"),taskArchive=document.querySelector(".task-archive__container"),taskBtnDone=(btnNewTask.addEventListener("click",()=>modal.style.display="block"),document.querySelectorAll(".task__btn")),getCheckBoxValue=()=>{for(i=0;i<checkBoxes.length;i++)if(checkBoxes[i].checked)return checkBoxes[i].value},todo=()=>{textLength.innerHTML=0,inputDesc.addEventListener("keydown",()=>{var e=inputDesc.value.length;if(textLength.innerHTML=0+e,4<=e)for(i=0;i<limitClass.length;i++)limitClass[i].style.color="red"}),form.addEventListener("submit",e=>{e.preventDefault();const t=document.createElement("li");t.className="task__item";var e=tasksList.firstChild,o=input.value,s=inputDesc.value,l=getCheckBoxValue();""===o&&(input.classList.add("modal__input--error"),console.log("error")),void 0===l?(checkBoxesContainer.classList.add("modal__checkboxes-- error"),console.log("Select priority please")):(input.classList.remove("modal__input--error"),checkBoxesContainer.classList.remove("modal__checkboxes-- error"),t.innerHTML=`
          
            <div class="task__head">
            <input class="task__btn" type="radio" id="done-task"> 
            <label class="task__btn--label" for="done-task"></label>
                <h4 class="task__title">${o}</h4>
                <span class="priority priority--${l}">${l}</span>
            </div>
            <p class="task__desc">${s}</p>
            
             `,tasksList.insertBefore(t,e),modal.style.display="none"),form.reset()}),tasksList.addEventListener("click",e=>{let t=e.target;console.log(t),t.classList.contains("task__btn")&&t.parentNode.parentNode.parentNode.removeChild(t.parentNode.parentNode)})};todo();